apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-act-runner
  namespace: sisyphus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-act-runner
  template:
    metadata:
      labels:
        app: gitea-act-runner
    spec:
      initContainers:
        - name: register
          image: gitea/act_runner:nightly
          imagePullPolicy: IfNotPresent
          workingDir: /data
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -f .runner ]; then
                act_runner register \
                  --instance http://gitea-http.sisyphus.svc.cluster.local:3000 \
                  --token "Cfcb3DhAQcQ05xuJr7G9iVCGRY1rB2Xbt516ENMe" \
                  --name kind-runner \
                  --labels self-hosted:docker://node:20
              fi
              echo "Registration done"
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: docker
          image: docker:24-dind
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - name: docker-data
              mountPath: /var/lib/docker
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
        - name: runner
          image: gitea/act_runner:nightly
          imagePullPolicy: IfNotPresent
          workingDir: /data
          command:
            - act_runner
            - daemon
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          emptyDir: {}
        - name: docker-data
          emptyDir: {}
