apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-act-runner
  namespace: sisyphus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-act-runner
  template:
    metadata:
      labels:
        app: gitea-act-runner
    spec:
      containers:
        - name: runner
          image: gitea/act_runner:nightly
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -f /data/.runner ]; then
                act_runner register --instance http://10.244.0.119:3000 --token "V0IVv4BVRrgcOWwmAEA5NGaIzdX7LVfWdm7yPnN7" --name kind-runner --labels self-hosted:docker://alpine:latest
              fi
              act_runner daemon
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          emptyDir: {}
