apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orchestrator.fullname" . }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
data:
  SISYPHUS_LOG_LEVEL: {{ .Values.env.log_level | quote }}
  SISYPHUS_LOG_JSON: {{ .Values.env.log_json | quote }}
  SISYPHUS_BKD_BASE_URL: {{ .Values.env.bkd_base_url | quote }}
  SISYPHUS_WORKDIR_ROOT: {{ .Values.env.workdir_root | quote }}
  SISYPHUS_BKD_PROJECT_ID: {{ .Values.env.bkd_project_id | quote }}
  SISYPHUS_REPO_URL: {{ .Values.env.repo_url | quote }}
